### PR TITLE
Petsc4py needs to be rebuild against PETSc for HDF5 support

### PR DESCRIPTION
**Pull request by rbeucher**
The PETSc-feedstock supports HDF5 now. 
Petsc4py needs to be rebuild against PETSc to have HDF5 support.

Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rbeucher** [comment]
@conda-forge-admin, please rerender

**Comment by dalcinl** [comment]
@rbeucher Can you please look at the build logs and confirm that all of them used a petsc package version depending on HDF5?

**Comment by rbeucher** [comment]
OK where do I look?

**Comment by dalcinl** [comment]
> OK where do I look?

Oh, you have to expand the list of checks, click in details, and go one by one through the logs in the various CI services. Annoying, I know, but we do not have any other way to make sure the petsc4py packages will have HDF5 support.

**Comment by rbeucher** [comment]
OK it looks good to me, they all have hdf5.

**Pull request merged**
